name: Build from pull request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Figure out if running fork PR
        id: fork
        run: '["${{ secrets.DOCKER_REGISTRY_TOKEN }}" == ""] && echo "::set-output name=is_fork_pr::true" || echo "::set-output name=is_fork_pr::false"'

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
        if: steps.fork.outputs.is_fork_pr == 'false'

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.x'

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: -p bugs -p unused --timeout=3m

      - name: Build
        run: |
          export GIT_TAG_NAME=${GITHUB_HEAD_REF##*/}
          make dockerimages

      - name: Push
        run: |
          export GIT_TAG_NAME=${GITHUB_HEAD_REF##*/}
          make dockerpush
        if: steps.fork.outputs.is_fork_pr == 'false'
